### ISSUE TITLE
当前版本连接MySQL报错

### ISSUE THREAD

**Issue by dimplememory** [liukefeng2008/idea-plugin-jpa-support#14]
Error: Unable to connect to the database. (1193,HY000,Unknown system variable 'query_cache_size')
IDEA中自带工具与DB能正常连接

**Comment by dimplememory** [comment]
java.sql.SQLException: Unknown system variable 'query_cache_size'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at com.mysql.cj.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:2831)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:2381)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1739)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.ifengxue.plugin.JpaSupport.lambda$null$8(JpaSupport.java:183)
	at java.lang.Thread.run(Thread.java:748)

**Comment by engineer-myoa** [comment]
in build.gradle,

```
    compile group: 'mysql', name: 'mysql-connector-java', version: '6.0.6'
```
jpa-support are using mysql connector 6.0.6.

The query_cache_size parameter is deprecated in MySQL 8. Please read below refer.
https://dev.mysql.com/doc/refman/5.7/en/query-cache.html

If you need temporarily using it, Try this one. 
https://mvnrepository.com/artifact/mysql/mysql-connector-java/5.1.44
compile group: 'mysql', name: 'mysql-connector-java', version: '5.1.44'

Or latest one.
https://mvnrepository.com/artifact/mysql/mysql-connector-java/8.0.15
compile group: 'mysql', name: 'mysql-connector-java', version: '8.0.15'

**Comment by liukefeng2008** [comment]
[Jpa.Support-1.1.2.zip](https://github.com/liukefeng2008/idea-plugin-jpa-support/files/3355548/Jpa.Support-1.1.2.zip)

这是最新的版本，看看能不能解决你的问题
