### ISSUE TITLE
When connect to Postgre DB, it shows IllegalArgumentException in JpaSupport.java:429

### ISSUE THREAD

**Issue by samsamyung** [liukefeng2008/idea-plugin-jpa-support#15]
I think when creating directories in JpaSupport.java:429, the path should use '/' instead of '\', just like what the error message suggested.

java.lang.IllegalArgumentException: separators must be '/'; path is C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4\bin\driver_vendor
	at com.intellij.ide.util.DirectoryUtil.mkdirs(DirectoryUtil.java:46)
	at com.ifengxue.plugin.JpaSupport$DownloadDriverRunnable.lambda$run$1(JpaSupport.java:429)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:263)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:319)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:321)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:353)
	at com.ifengxue.plugin.JpaSupport$DownloadDriverRunnable.run(JpaSupport.java:427)
	at com.ifengxue.plugin.JpaSupport.lambda$actionPerformed$3(JpaSupport.java:117)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:868)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:517)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:686)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by liukefeng2008** [comment]
[Jpa Support-1.1.1.zip](https://github.com/liukefeng2008/idea-plugin-jpa-support/files/3150953/Jpa.Support-1.1.1.zip)

You can temporarily install this version of the plugin.

**Comment by samsamyung** [comment]
Hi,

Thanks for your temporary solution. The error did not show, but after
connecting to my postgresql, no table appears in the dialog for me to
select.

[image: image.png]

**Comment by liukefeng2008** [comment]
You should look here. [PostgreSQLDriverAdapter.java#L29](https://github.com/liukefeng2008/idea-plugin-jpa-support/blob/master/src/main/java/com/ifengxue/plugin/adapter/PostgreSQLDriverAdapter.java#L29)

```
@Override
  public List<TableSchema> findDatabaseSchemas(String database) throws SQLException {
    FastJdbc fastJdbc = Holder.getFastJdbc();
    return fastJdbc.find("select a.relname as name , b.description as comment from pg_class a\n"
        + "left join (select * from pg_description where objsubid =0 ) b on a.oid = b.objoid\n"
        + "where a.relname in (select tablename from pg_tables where schemaname = 'public')", (row, rowNum) -> {
      TableSchema tableSchema = new TableSchema();
      tableSchema.setTableName(row.getString("name"));
      tableSchema.setTableComment(Optional.ofNullable(row.getString("comment")).orElse(""));
      tableSchema.setTableSchema("public");
      return tableSchema;
    });
  }
```
