### ISSUE TITLE
连接数据库报错

### ISSUE THREAD

**Issue by tinyalley** [liukefeng2008/idea-plugin-jpa-support#18]
- idea: 2019.1.3
- 数据库：mariadb 10.4
- 错误信息：

```
java.lang.NoClassDefFoundError: java/sql/Driver
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:306)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:302)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:271)
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at com.ifengxue.plugin.JpaSupport.lambda$null$8(JpaSupport.java:157)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: java.sql.Driver
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:257)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
```

**Comment by liukefeng2008** [comment]
是否可以使用jdk8环境再试一下呢？

**Comment by tinyalley** [comment]
> 是否可以使用jdk8环境再试一下呢？

可以了、之前是我用 JBR11的原因、谢谢
