### ISSUE TITLE
Unable to load authentication plugin 'caching_sha2_password'.

### ISSUE THREAD

**Issue by NirReigo** [liukefeng2008/idea-plugin-jpa-support#19]
setup
1 ) IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

2) DB - mySQL version - 8.0.16 .
On connection window I only have option to mySql6.0.6

press on next and got this error .
Error: Unable to connect to the database. (0,S1009,Unable to load authentication plugin 'caching_sha2_password'.)

StackTrace here 
--------------------

connect to database failed

java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:78)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.ifengxue.plugin.JpaSupport.lambda$null$8(JpaSupport.java:183)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.core.exceptions.WrongArgumentException: Unable to load authentication plugin 'caching_sha2_password'.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(MysqlaAuthenticationProvider.java:564)
	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.connect(MysqlaAuthenticationProvider.java:204)
	at com.mysql.cj.mysqla.io.MysqlaProtocol.connect(MysqlaProtocol.java:1414)
	at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:132)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1726)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
	... 7 more

**Comment by liukefeng2008** [comment]
[Jpa.Support-1.1.2.zip](https://github.com/liukefeng2008/idea-plugin-jpa-support/files/3355548/Jpa.Support-1.1.2.zip)

Please use this version, this version supports 3 mysql driver versions(5.x 6.x 8.x), look forward to your feedback

**Comment by NirReigo** [comment]
Hi , 
I can see on the db versions drop-down entriy for mySql 8 .
when I try to generate I first got the same error , I do need to execute this command - 
ALTER USER 'student'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass123';

after did that and try again with mysql 8 - got this error - 
Error: Unable to connect to the database. (1193,HY000,Unknown system variable 'query_cache_size')
read this [](https://stackoverflow.com/questions/49984267/java-sql-sqlexception-unknown-system-variable-query-cache-size
)
so I try to change db version to 5.1.47 , and all work as expected - although I am working with mysql 8

**Comment by liukefeng2008** [comment]
> [Jpa.Support-1.1.2.zip](https://github.com/liukefeng2008/idea-plugin-jpa-support/files/3355548/Jpa.Support-1.1.2.zip)
> 
> Please use this version, this version supports 3 mysql driver versions(5.x 6.x 8.x), look forward to your feedback


You can upgrade version to this, this version support `Mysql 8.x` driver.

**Comment by NirReigo** [comment]
Hi , not work for me .. , not find jdbc driver .
check stacktrace ..

Inteliji version - 
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

java.lang.NoClassDefFoundError: java/sql/Driver
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:280)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.ifengxue.plugin.JpaSupport.lambda$null$8(JpaSupport.java:160)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: java.sql.Driver
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:282)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more

**Comment by liukefeng2008** [comment]
> Hi , not work for me .. , not find jdbc driver .
> check stacktrace ..
> 
> Inteliji version -
> IntelliJ IDEA 2019.2 (Ultimate Edition)
> Build #IU-192.5728.98, built on July 23, 2019
> Runtime version: 11.0.3+12-b304.10 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> 
> java.lang.NoClassDefFoundError: java/sql/Driver
> at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
> at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
> at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
> at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
> at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
> at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:280)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> at java.base/java.lang.Class.forName0(Native Method)
> at java.base/java.lang.Class.forName(Class.java:398)
> at com.ifengxue.plugin.JpaSupport.lambda$null$8(JpaSupport.java:160)
> at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.lang.ClassNotFoundException: java.sql.Driver
> at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:282)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> ... 13 more

This version current support jdk9+,

**Comment by liukefeng2008** [comment]
I am looking for a way to get it to run in IDEA 2019.2+
