### ISSUE TITLE
idea 2019.3 jdk11 jdk13 报错 java.lang.NoClassDefFoundError: java/sql/Driver

### ISSUE THREAD

**Issue by walnut-tom** [liukefeng2008/idea-plugin-jpa-support#41]
java.lang.NoClassDefFoundError: java/sql/Driver
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:359)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:355)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:305)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at com.ifengxue.plugin.JpaSupport.lambda$null$8(JpaSupport.java:157)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: java.sql.Driver
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:307)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more

**Comment by liukefeng2008** [comment]
暂时还不支持jdk9+，目前还未找到解决版本

**Comment by liukefeng2008** [comment]
@walnut-tom  当前最新版本 [1.1.5](https://plugins.jetbrains.com/plugin/10707-jpa-support/versions)已经支持JDK 9+了，可以下载尝试

**Comment by liukefeng2008** [comment]
最新版已经修复这个bug.[1.1.6](https://plugins.jetbrains.com/plugin/10707-jpa-support/update/76105)
